// --- records ---
// This table stores the last random number generated by the RNG Oracle.
// It helps to understand how to use this table.


// scope: contract
// row: unic row that stores the last random number generated by the RNG Oracle

TABLE records_table {
    uint64_t request_id;
    uint64_t min;
    uint64_t max;
    name caller;

    uint64_t number;
    uint64_t primary_key() const { return request_id; }
    EOSLIB_SERIALIZE(records_table, (request_id)(caller)(min)(max))
};
typedef eosio::multi_index<"records"_n, records_table > records;